services:

  # Nginx service
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro   # Nginx conf folder
      - ./nginx/log/:/var/log/nginx:rw        # Log folder
      - ./certbot/www/:/var/www/certbot/:ro   # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:ro  # Certbot folder
      - ./blog/public/:/var/www/public:ro    # Zola site public folder
    networks:
      - local-net
    depends_on:
      - jenkins   # Need to know jenkins host for reverse proxy
      - mirotalk

  # Lets Encrypt service
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw   # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:rw  # Certbot etc folder
    depends_on:
      - webserver # Need webserver to run

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - ./jenkins/config/:/var/jenkins_home:rw # Jenkins config folder
    networks:
      - local-net

  # Zola service
  zola:
    image: zola:custom
    build: ./zola
    entrypoint: /usr/bin/zola
    volumes:
      - ./blog:/blog # Mount blog into the container

  # Mirotalk
  mirotalk:
    image: mirotalksfu:custom
    build:
      context: .
      dockerfile: ./mirotalk/Dockerfile
    volumes:
      - ./mirotalk/config.js:/src/app/src/config.js:ro
    ports:
      - '40000-40100:40000-40100/tcp'
      - '40000-40100:40000-40100/udp'
    networks:
      - local-net

networks:
  local-net:
